sudo: false
language: node_js
node_js:
  - '12'
branches:
  only:
    - dev
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
  - npm test
  - npm run coveralls
